export const EXPORT_OPTIONS_DEFAULT = {
  includeCurrentArrangement: true,
  includeDefaultArrangement: true,
  includeTitleSlide: true,
  addBlankSlideBeforeTitle: true,
  includeLanguage2: true,
};

export const EXPORT_TEMPLATE_DEFAULT = {
  language1: {
    name: "Lang1",
    x: 0,
    y: 0,
    width: 1920,
    height: 540,
    align: "center",
    justify: "center",
    fontSize: 104,
    fontFamily: "Noto Sans TC",
    fontWeight: "bold",
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  language2: {
    name: "Lang2",
    x: 0,
    y: 540,
    width: 1920,
    height: 540,
    align: "center",
    justify: "center",
    fontSize: 48,
    fontFamily: "Noto Sans TC",
    fontWeight: "bold",
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  title1: {
    name: "Title1",
    x: 0,
    y: 0,
    width: 1920,
    height: 540,
    align: "center",
    justify: "center",
    fontSize: 120,
    fontFamily: "Noto Sans TC",
    fontWeight: "bold",
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  title2: {
    name: "Title2",
    x: 0,
    y: 540,
    width: 1920,
    height: 540,
    align: "center",
    justify: "center",
    fontSize: 56,
    fontFamily: "Noto Sans TC",
    fontWeight: "bold",
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  title3: {
    name: "Title3",
    x: 0,
    y: 1080,
    width: 1920,
    height: 540,
    align: "center",
    justify: "center",
    fontSize: 56,
    fontFamily: "Noto Sans TC",
    fontWeight: "bold",
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 2,
    hidden: true,
  },
};
